run:
  skip-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  enable:
    - dogsled
    - dupl
    - whitespace
    - wsl
    - exportloopref
  presets:
    - bugs
    - unused
  fast: false
