version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    ldflags:
      - >-
        -s -w
        -X main.version={{.Version}}
        -X main.commit={{.Commit}}
release:
  draft: true
  github:
    owner: martialblog
    name: dummy_exporter
archives:
  - formats: binary
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- if eq .Os "linux" }}Linux{{ end }}
      {{- if eq .Os "darwin" }}Darwin{{ end }}
      {{- if eq .Arch "amd64" }}_x86_64{{ end }}
      {{- if eq .Arch "arm64" }}_arm64{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
