---
metric_name:
  labels:
    - label1: http,https
    - label2: bar,foo
  type: gauge
  range: 0,10
metric_name_total:
  labels:
    - label1: http,https
    - label2: bar,foo
  type: counter
  range: 0,10
